version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-system-watcher-app
    volumes:
      - ./:/app
      - /app/vendor # Don't mount host vendor directory
      - /app/node_modules # Don't mount host node_modules
    environment:
      - APP_ENVIRONMENT=docker
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-sail}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: file-system-watcher-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-sail}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local